### ISSUE TITLE
Async callback on websocket read

### ISSUE THREAD

**Issue by 42phoenix42** [yufuquant/rust-bybit#26]
Hi, I'm still learning Rust and may be someone could help me with this problem.

I'm trying to save message from WS and have troubles with async call, may be you can help me? 

```
client.run(|res| {
    tokio::spawn(async {
        if let Err(err) = clickhouse::insert_exchange_futures(res).await {
            eprintln!("Error inserting trade into ClickHouse: {:?}", err);
        }
    });
}).expect("TODO: panic message");
```
And error is "borrowed data escapes outside of closure / `res` escapes the closure body here argument requires that `'1` must outlive `'static`". As I understand the problem is that I can't move `res` outside of callback, but how I can save it or do something like clone and pass cloned variable. 

Is there any way to do it in another way instead of change something inside lib or doing own lib from scratch?

Thanks!

**Comment by Sild** [comment]
`res` (especially res.data for `SpotPublicResponse::Trade`) contains many references which can't be handled out of callback scope

I mitigate it by copying all important data to object which really own the data.
For example, with Trade:

```
pub struct TradeRaw {
    pub ts_ms: u128,
    pub symbol: String,
    pub is_buy: bool,
    pub vol: f64,
    pub price: f64,
    pub id: String,
}

impl From<&Trade<'_>> for TradeRaw {
    fn from(trade: &Trade) -> Self {
        let vol = trade.v.parse::<f64>().unwrap_or(-1.0);
        if vol.eq(&-1.0) {
            log::error!("Fail to get vol from trade: {:?}", trade);
        }
        let price = trade.p.parse::<f64>().unwrap_or(-1.0);
        if price.eq(&-1.0) {
            log::error!("Fail to get price from trade: {:?}", trade);
        }

        TradeRaw {
            ts_ms: trade.T as u128,
            symbol: trade.s.to_string(),
            is_buy: trade.S == "Buy",
            vol,
            price,
            id: trade.i.to_string(),
        }
    }
}
```

Then you can work with `TradeRaw` asynchronously.

Probably you also must move `TradeRaw` to coroutine instead of taking a reference

As an advice for learning, I would suggest to use threads instead of coroutines for beginning - it's behaviour more predictable =)

**Comment by 42phoenix42** [comment]
Thank you very much for the clarification!
Maybe someone will find an example useful (maybe not perfect, but working :laughing:):
```
    if let Err(e) = client.run(|res| match res {
        FuturePublicResponse::Orderbook(res) => println!("Orderbook: {:?}", res),
        FuturePublicResponse::Trade(res) => {
            let mut trades: Vec<TradeRaw> = vec![];

            for trade in &res.data {
                trades.push(TradeRaw::from(trade));
            }

            tokio::spawn(async move {
                if let Err(err) = clickhouse::insert_exchange_futures(trades).await {
                    eprintln!("Error inserting trade into ClickHouse: {:?}", err);
                }
            });
        },
        FuturePublicResponse::Ticker(res) => println!("Ticker: {:?}", res),
        FuturePublicResponse::Kline(res) => println!("Kline: {:?}", res),
        FuturePublicResponse::Liquidation(res) => println!("Liquidation: {:?}", res),
        FuturePublicResponse::Op(res) => println!("Op: {:?}", res),
    }) {
        eprintln!("Error: {e}")
    }
```
